<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/1_16_Functions.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

## ðŸŸ© Job Title Contains (1.16.1)

In [11]:
# Code Needed
job_title = 'Data Scientist'
keyword = 'Data'
def job_title_contains(job_title,keyword):
  return keyword in job_title


job_title_contains(job_title,keyword)

True

---

## ðŸŸ© Average Salary (1.16.2)

In [21]:
# Code Needed
salaries = [95000, 120000, 105000, 90000, 130000]

def average_salary(salaries):
    avg_salary = sum (salaries) / len(salaries)
    return avg_salary

average_salary(salaries)

108000.0

---

## ðŸŸ¨ Salary Statistics (1.16.3)

In [25]:
# Code Needed
salaries = [95000, 120000, 105000, 90000, 130000]

def salary_statistics(salaries):
  return  {'Minimum' : [min(salaries)] , 'Maximum' : [max(salaries)] , 'Average' : [sum(salaries) / len(salaries)]}

salary_statistics(salaries)

{'Minimum': [90000], 'Maximum': [130000], 'Average': [108000.0]}

---

## ðŸŸ¥ Job Posting Summary (1.16.4)

In [36]:
# Code Needed
job_postings = [
    {'title': 'Data Scientist', 'location': 'New York', 'salary': 95000},
    {'title': 'Data Analyst', 'location': 'San Francisco', 'salary': 85000},
    {'title': 'Machine Learning Engineer', 'location': 'New York', 'salary': 115000}
]

def job_posting_summary(job_postings):
    total_postings = len(job_postings)
    total_salary = sum(posting['salary'] for posting in job_postings)
    average_salary = total_salary / total_postings
    unique_locations = list(set(posting['location'] for posting in job_postings))
    return {
        'total_postings': total_postings,
        'average_salary': average_salary,
        'unique_locations': unique_locations
    }
job_posting_summary(job_postings)

{'total_postings': 3,
 'average_salary': 98333.33333333333,
 'unique_locations': ['New York', 'San Francisco']}

---