<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/1_21_Classes.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

## ðŸŸ© Create JobPosting Class (1.21.1)

In [1]:
# Create the JobPostings class in this code cell

In [2]:
# Code Needed

class JobPosting:
    def __init__(self, title, company, location):
        self.title = title
        self.company = company
        self.location = location

job = JobPosting('Data Scientist', 'Tech Innovations', 'New York')

print(job.title)
print(job.company)
print(job.location)

Data Scientist
Tech Innovations
New York

---

## ðŸŸ¨ Convert to Dictionary (1.21.2)

In [3]:
# Create the JobPostings class in this code cell

In [12]:
# Code Needed
import pandas as pd

class JobPosting:
  def __init__(self,title,company,location,salary):
    self.title = title
    self.company = company
    self.location = location
    self.salary = salary

  def to_dict(self):
        return {
            'title': self.title,
            'company': self.company,
            'location': self.location,
            'salary': self.salary
        }


job = JobPosting('Data Scientist', 'Tech Innovations', 'New York', 120000)
print(job.to_dict())

{'title': 'Data Scientist', 'company': 'Tech Innovations', 'location': 'New York', 'salary': 120000}

---

## ðŸŸ¥ Compare Job Salaries (1.21.3)

In [5]:
# Create the JobPostings class in this code cell

In [26]:
# Code Needed
job1 = JobPosting('Data Scientist', 'Tech Innovations', 'New York', 120000)
job2 = JobPosting('Data Analyst', 'Data Driven Co', 'San Francisco', 100000)

class JobPosting:
  def __init__(self,title,company,location,salary):
    self.title = title
    self.company = company
    self.location = location
    self.salary = salary

  def compare_salary(self, other_job):
        if self.salary > other_job.salary:
            return self.title
        else:
            return other_job.title

job1 = JobPosting('Data Scientist', 'Tech Innovations', 'New York', 120000)
job2 = JobPosting('Data Analyst', 'Data Driven Co', 'San Francisco', 100000)

print(job1.compare_salary(job2))

Data Scientist

---